"""Subclass of EmptyPanel, which is generated by wxFormBuilder."""

import wx
import MainBase

# Implementing EmptyPanel
class MyEmptyPanel( MainBase.EmptyPanel ):
	def __init__( self, parent ):
		MainBase.EmptyPanel.__init__( self, parent )
	
