"""Subclass of FrameBase, which is generated by wxFormBuilder."""

import wx
import MainBase

# Implementing FrameBase
class MyFrameBase( MainBase.FrameBase ):
	def __init__( self, parent ):
		MainBase.FrameBase.__init__( self, parent )
	
