# -*- coding: utf-8 -*-


VIEW_OPTION_NAME_MAIN = "总览"
VIEW_OPTION_NAME_DEVICE = "设备"
DEVICE_NAME_TRANSPORT = "皮带机"



ADD_DEVICE_LABEL_NAME = "名称:"
ADD_DEVICE_LABEL_POS = "位置:"
ADD_DEVICE_LABEL_DESC = "描述:"



MODULE_TYPE_SIG_IN = 1
MODULE_TYPE_VAL_IN = 2
MODULE_TYPE_SIG_OUT = 3

MODULE_TYPE_LIST = {
MODULE_TYPE_SIG_IN : "信号量输入",
MODULE_TYPE_VAL_IN : "数值量输入",
MODULE_TYPE_SIG_OUT : "信号量输出",
}


