"""Subclass of MyPanel2, which is generated by wxFormBuilder."""

import wx
import MainBase

# Implementing MyPanel2
class MyMyPanel2( MainBase.MyPanel2 ):
	def __init__( self, parent ):
		MainBase.MyPanel2.__init__( self, parent )
	
