"""Subclass of PanelBase, which is generated by wxFormBuilder."""

import wx
import MainBase

# Implementing PanelBase
class MyPanelBase( MainBase.PanelBase ):
	def __init__( self, parent ):
		MainBase.PanelBase.__init__( self, parent )
	
